name: "publish npm"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Authenticate with GitHub NPM package repository
              run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PUBLISH_NPM_TOKEN }}" >> ~/.npmrc
            - name: publish
              run: npm publish --access public
              working-directory: .
    
