name: "publish npm"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
            - name: Use npmrc
              uses: actions/setup-node@v2
              with:
                  registry-url: ${{ secrets.NPM_REGISTRY_URL }} # Define secret for registry URL
                  cache: 'npm'
            - name: publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
